name: Storybook

on: [push]

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm --prefix stories run install
      - run: npm --prefix stories run build-storybook
